# Site settings
title: Senpai Dev Labs
email: hello@senpaidev.com
description: "Simple and fun"
info: "Ninja apps, built for humans"
message: "Ninja apps, built for humans"
keywords: "mac,apple,iphone,ios,osx,games,apps,development,senpaidev,senpai dev labs,motivational,motivational daily"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.senpaidev.com" # the base hostname & protocol for your site
twitter_username: senpaidevlabs
# Build settings
markdown: kramdown
author:
    name: Kenny Meyer
    twitter: meyerkenny
    url: https://www.kennymeyer.net
    header_bg: /images/profile-header.png
    avatar: https://www.kennymeyer.net/img/me.jpg
    email: kenny@senpaidev.com
facebook:
    image: /images/delightfuldev-facebook-cover.png
